### ISSUE TITLE
plot_cladogram error: argument "caller_env" is missing, with no default

### ISSUE THREAD

**Issue by jarrodscott** [yiluheihei/microbiomeMarker#36] opened 2021-05-14 20:43 UTC
Hi! 

I am getting an error when I use `plot_cladogram` on the example data:

`Error in DataMask$new(.data, caller_env) : argument "caller_env" is missing, with no default`

minimal working example:

```
# Works fine
mm <- lefse(
  spontaneous_colitis, 
  norm = "CPM", 
  class = "class", 
  multicls_strat = TRUE
)
```

```
# Works fine
plot_ef_bar(mm, label_level = 1) +
            scale_fill_manual(values = c("rag2" = "blue", "truc" = "red"))
```
```
#ERROR
plot_cladogram(mm, color = c("blue", "red"))
```
`Error in DataMask$new(.data, caller_env) : argument "caller_env" is missing, with no default`

I search around for the but was not able to find anything that could solve this issue. I think maybe this has something to do with `rlang` but cannot be sure. Any help would be most appreciated!

This is a wonderful package by the way :)

<details markdown="1">
<summary>sessionInfo, loaded microbiomeMarker only</summary>

```
> sessionInfo()
R version 4.0.5 (2021-03-31)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] microbiomeMarker_0.0.1.9000

loaded via a namespace (and not attached):
  [1] Rtsne_0.15                  colorspace_2.0-1            ggtree_2.4.2                rjson_0.2.20                ellipsis_0.3.2             
  [6] circlize_0.4.12             XVector_0.30.0              GenomicRanges_1.42.0        GlobalOptions_0.1.2         aplot_0.0.6                
 [11] clue_0.3-59                 bit64_4.0.5                 AnnotationDbi_1.52.0        fansi_0.4.2                 codetools_0.2-18           
 [16] splines_4.0.5               cachem_1.0.4                geneplotter_1.68.0          ade4_1.7-16                 jsonlite_1.7.2             
 [21] phyloseq_1.34.0             nloptr_1.2.2.2              Cairo_1.5-12.2              annotate_1.68.0             cluster_2.1.1              
 [26] png_0.1-7                   BiocManager_1.30.15         compiler_4.0.5              httr_1.4.2                  rvcheck_0.1.8              
 [31] lazyeval_0.2.2              assertthat_0.2.1            Matrix_1.3-2                fastmap_1.1.0               limma_3.46.0               
 [36] prettyunits_1.1.1           tools_4.0.5                 igraph_1.2.6                gtable_0.3.0                glue_1.4.2                 
 [41] GenomeInfoDbData_1.2.4      reshape2_1.4.4              dplyr_1.0.6                 Rcpp_1.0.6                  Biobase_2.50.0             
 [46] vctrs_0.3.8                 Biostrings_2.58.0           rhdf5filters_1.2.1          multtest_2.46.0             ape_5.5                    
 [51] nlme_3.1-152                iterators_1.0.13            ANCOMBC_1.0.5               stringr_1.4.0               rbibutils_2.1.1            
 [56] lifecycle_1.0.0             gtools_3.8.2                XML_3.99-0.6                zlibbioc_1.36.0             MASS_7.3-53.1              
 [61] scales_1.1.1                hms_1.0.0                   MatrixGenerics_1.2.1        parallel_4.0.5              SummarizedExperiment_1.20.0
 [66] biomformat_1.18.0           metagenomeSeq_1.32.0        rhdf5_2.34.0                RColorBrewer_1.1-2          yaml_2.2.1                 
 [71] ComplexHeatmap_2.6.2        memoise_2.0.0               ggplot2_3.3.3               stringi_1.5.3               RSQLite_2.2.7              
 [76] genefilter_1.72.1           S4Vectors_0.28.1            foreach_1.5.1               tidytree_0.3.3              permute_0.9-5              
 [81] caTools_1.18.2              BiocGenerics_0.36.1         BiocParallel_1.24.1         shape_1.4.5                 GenomeInfoDb_1.26.7        
 [86] Rdpack_2.1.1                rlang_0.4.11                pkgconfig_2.0.3             matrixStats_0.58.0          bitops_1.0-7               
 [91] Wrench_1.8.0                lattice_0.20-41             purrr_0.3.4                 Rhdf5lib_1.12.1             treeio_1.14.4              
 [96] patchwork_1.1.1             bit_4.0.4                   tidyselect_1.1.1            plyr_1.8.6                  magrittr_2.0.1             
[101] DESeq2_1.30.1               R6_2.5.0                    gplots_3.1.1                IRanges_2.24.1              generics_0.1.0             
[106] DelayedArray_0.16.3         DBI_1.1.1                   pillar_1.6.0                mgcv_1.8-34                 survival_3.2-10            
[111] RCurl_1.98-1.3              tibble_3.1.1                crayon_1.4.1                KernSmooth_2.23-18          utf8_1.2.1                 
[116] microbiome_1.12.0           GetoptLong_1.0.5            progress_1.2.2              locfit_1.5-9.4              grid_4.0.5                 
[121] data.table_1.14.0           blob_1.2.1                  vegan_2.5-7                 digest_0.6.27               xtable_1.8-4               
[126] tidyr_1.1.3                 glmnet_4.1-1                stats4_4.0.5                munsell_0.5.0           
```
</details>

**Comment by yiluheihei** [comment] 2021-05-18 03:17
@jarrodscott  Thanks for your interest in  microbiomeMarker.

Please provide a reproducible example, it will be much easier to solve your problem.

**Comment by jarrodscott** [comment] 2021-05-18 12:12
Hi @yiluheihei . Sorry, thought I did :) I am getting the error with the example data sets in the package. I can also send you my data if you need that. 

for example, both of these return the same error:

```
data("spontaneous_colitis")
mm <- lefse(
  spontaneous_colitis, 
  norm = "CPM", 
  class = "class", 
  multicls_strat = TRUE
)
plot_cladogram(mm, color = c("blue", "red"))
```
```
data("pediatric_ibd")
mm_2 <- lefse(
  pediatric_ibd, 
  class = "Class", 
  norm = "CPM", 
  multicls_strat = TRUE
)
marker_table(mm_2)
plot_cladogram(mm_2, color = c("blue", "red"))
```

Here is the traceback from RStudio. I get the same error if I just run in R.

```
Error in DataMask$new(.data, caller_env) : argument "caller_env" is missing, with no default
17. initialize(...)
16. DataMask$new(.data, caller_env)
15. mutate_cols(.data, ...)
14. mutate.data.frame(., isTip = !.data$node %in% .data$parent)
13. NextMethod()
12. mutate.tbl_tree(., isTip = !.data$node %in% .data$parent)
11. mutate(., isTip = !.data$node %in% .data$parent)
10. as_tibble(model) %>% mutate(isTip = !.data$node %in% .data$parent)
9. fortify.phylo(model, data, layout = layout, yscale = yscale, ladderize = ladderize, right = right, branch.length = branch.length, mrsd = mrsd, as.Date = as.Date, ...)
8. fortify.treedata(data, ...)
7. fortify(data, ...)
6. ggplot.default(tr, mapping = mapping, layout = layout, mrsd = mrsd, as.Date = as.Date, yscale = yscale, yscale_mapping = yscale_mapping, ladderize = ladderize, right = right, branch.length = branch.length, root.position = root.position, ...)
5. ggplot(tr, mapping = mapping, layout = layout, mrsd = mrsd, as.Date = as.Date, yscale = yscale, yscale_mapping = yscale_mapping, ladderize = ladderize, right = right, branch.length = branch.length, root.position = root.position, ...)
4. ggtree::ggtree(treedata, size = size, layout = layout)
3. generate_taxa_tree(., size = branch_size)
2. get_treedata_phyloseq(ps) %>% generate_taxa_tree(size = branch_size)
1. plot_cladogram(mm_2, color = c("blue", "red"))
```

**Comment by yiluheihei** [comment] 2021-06-01 00:49
@jarrodscott Please update all the dependent packages to the latest version and try again.

**Comment by yiluheihei** [comment] 2021-11-23 08:07
Close it since I can not reproduce the error.

**Closed** 2021-11-23 08:06 UTC
